### ISSUE TITLE
Ai mod issue from website?

### ISSUE THREAD

**Issue by mwdglock** [recursiveGecko/hub#4]
After most recent patch when running only this AI mod players will get kicked out/frozen on restart. It is not every time but can be often. Removed the AI mod and no one has been kicked/froze on restart from my server since. Tried a recently updated AI mod because I heard the update caused issues with wedges and certain suspect behaviors. No freezes or kicks since and its been 2 days. Did not have this issue before and I host a server of 30 ppl and they all use my mod I created with your website. Any help will be appreciated.

**Comment by recursiveGecko** [comment]
Hi, did you resolve the issue? What happened?
